import json
import re
from state.analyst_state import AnalystState
from utils.llm_client import invoke_llm

def insight_generator(state: AnalystState) -> dict:
    """
    Agent 3 — Insight Generator
    Enhanced prompt with persona-driven reasoning and structured analytical layers.
    """
    eda_results = state["eda_results"]
    eda_json = json.dumps(eda_results, indent=2, default=str)

    # Prevent token overflow while maintaining data integrity
    if len(eda_json) > 12000: # Increased slightly if model window allows
        eda_json = eda_json[:12000] + "\n... [Data Truncated]"

    prompt = f"""
### ROLE
You are a Lead Data Scientist and Business Intelligence Consultant. Your goal is to transform raw Exploratory Data Analysis (EDA) metrics into actionable strategic intelligence.

### INPUT DATA (JSON)
{eda_json}

### TASK
Analyze the provided EDA results and extract 5–7 sophisticated insights. Do not simply restate the numbers; explain their significance.

### ANALYTICAL FRAMEWORK
1. **Distribution & Variance**: How spread is the data? Identify if the "average" is misleading due to outliers.
2. **Correlation & Causality**: Look for relationships between columns. If Column A increases, what happens to Column B?
3. **Data Quality & Anomalies**: Point out unexpected zeros, nulls, or extreme values that could skew results.
4. **Business Impact**: Translate a statistical finding into a potential real-world outcome (e.g., "The high variance in 'shipping_time' suggests supply chain instability").

### CONSTRAINTS
- **Precision**: Reference exact column names in **bold**.
- **Quantification**: Use specific figures, growth rates, or standard deviations.
- **Tone**: Professional, skeptical, and analytical. 
- **Format**: Return ONLY a numbered list. No intro or outro text.

### OUTPUT EXAMPLE
1. Significant **Skewness** detected in 'Revenue': 80% of total income is generated by only 5% of 'Customer_ID's, indicating a high dependency on power users.
2. Moderate **Correlation** (r=0.65) found between 'Ad_Spend' and 'Conversion_Rate', though the relationship breaks down after the $500 threshold.
"""

    try:
        response = invoke_llm(prompt, agent_id=3)
    except Exception as e:
        return {"insights": [f"LLM Error: {str(e)}"]}

    # Parsing logic
    lines = [
        line.strip()
        for line in response.strip().split("\n")
        if re.match(r"^\d+[\).\-\s]", line.strip())
    ]

    insights = lines if lines else [response.strip()]
    return {"insights": insights}